name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm ci
      - run: npm test

      # Check code formatting with Prettier
      - name: Check code format with Prettier
        run: npx prettier --check .

      # Lint the code with ESLint
      - name: Lint with ESLint
        run: npx eslint .

      # Run tests with Jest
      - name: Run tests with Jest
        run: npm test

      # Security scan with Snyk
      - name: Security scan with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Gitleaks - actions
      - name: Scan repository for secrets
        uses: zricethezav/gitleaks-action@v1
        with:
          args: detect --source .
